feat: support messaging between microservices for aca lab
Azure-Samples/java-microservices-aca-lab pull request #28
Opened 2024-09-12 07:19 UTC by haoozhang

## Purpose

Add the module to support messaging between microservices for aca lab.

TODO: 
1. adjust the doc order and update the doc title.
2. replace the current image.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-09-12 07:47 UTC, frankliu20 requested changes

2024-09-12 07:47 UTC, frankliu20 commented on config/application.yml
> +        client-id: <your-identity-cliend-id>
Is this a must for all applications?
If not, shall we move it to the project-specific one

2024-09-12 07:47 UTC, frankliu20 commented on src/spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/entities/VisitRequest.java
> +    public VisitRequest() {
Just use loombok annotation

2024-09-12 07:47 UTC, frankliu20 commented on docs/08_lab_messaging/0801_application.yml
> +server:
Let's not introduce too many new application.yaml, pls check with @sonwan2020

2024-09-12 07:54 UTC, haoozhang commented on config/application.yml
> +        client-id: <your-identity-cliend-id>
not for all applications, but for two applications: `visits-service` and `message-emulator`, just similar as the MySQL configuration, which is placed in the base application yml.

2024-09-12 09:20 UTC, haoozhang commented on src/spring-petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/entities/VisitRequest.java
> +    public VisitRequest() {
updated.

2024-09-13 02:03 UTC, sonwan2020 commented on config/application.yml
> +      pricing-tier: premium
why the pricing-tier required in data plane?

2024-09-13 02:08 UTC, sonwan2020 commented on config/application.yml
> +        client-id: <your-identity-cliend-id>
shall we put placeholder here and use environment variables to set the servicebus  namespace and client id?
it is not easy to dynamically update the config servers on provision

2024-09-13 02:09 UTC, sonwan2020 commented on docs/08_lab_messaging/0801.md
> +1. Commit and push your changes to the remote repository.
For our one-click solution, we should get a environment without update the config server

2024-09-16 07:30 UTC, vermegi commented on docs/08_lab_messaging/0801_application.yml
> +server:
@frankliu20 during testing of the lab for other technologies (spring apps and AKS) we discovered that it was easier to give learners the full application.yml, so they can overrise their old one, rather then telling them which lines to edit in the application.yml. Doing it like this basically reduces the amount of errors make during the lab.

2024-09-18 03:16 UTC, haoozhang commented on config/application.yml
> +      pricing-tier: premium
Because only the `Standard` and `Premium` tier can support JMS protocol.
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-jms-support#configuration:~:text=spring.jms.servicebus.pricing%2Dtier

2024-09-18 03:22 UTC, haoozhang commented on docs/08_lab_messaging/0801.md
> +1. Commit and push your changes to the remote repository.
I have already updated the configuration yml file under `/config` to meet the one-click solution, so no need to update the config server in one-click solution.
In this step by step tutorial, I added this to explain in more details.

2024-09-18 05:53 UTC, haoozhang commented on config/application.yml
> +        client-id: <your-identity-cliend-id>
updated.

2024-09-18 07:04 UTC, frankliu20 approved these changes

2024-09-18 09:41 UTC, sonwan2020 commented on config/application.yml
> +      pricing-tier: premium
In my understanding, the tier info is a control plane property, you don't have to put it into data plane?
I did not find the code using the pricing-tier.

2024-09-18 09:46 UTC, sonwan2020 commented on docs/08_lab_messaging/0801.md
> +             client-id: ${CLIENT_ID}
add the queue name 'visits-requests' in the config is more easy to understand

2024-09-18 09:50 UTC, sonwan2020 commented on docs/08_lab_messaging/0801_application.yml
> +  datasource:
I suggest we add this config based on passwordless solution, see lab 4
You may update config based on https://github.com/Azure-Samples/java-microservices-aca-lab/blob/main/config/application.yml

2024-09-18 09:52 UTC, sonwan2020 commented on docs/08_lab_messaging/0802.md
> +     --env-vars APPLICATIONINSIGHTS_CONNECTION_STRING=$AI_CONNECTIONSTRING APPLICATIONINSIGHTS_CONFIGURATION_CONTENT='{"role": {"name": "api-gateway"}}' InstrumentationKey=$AI_CONNECTIONSTRING \
role -> name: messaging-emulator

2024-09-18 09:53 UTC, sonwan2020 commented on docs/08_lab_messaging/0802.md
> +     --env-vars APPLICATIONINSIGHTS_CONNECTION_STRING=$AI_CONNECTIONSTRING APPLICATIONINSIGHTS_CONFIGURATION_CONTENT='{"role": {"name": "api-gateway"}}' InstrumentationKey=$AI_CONNECTIONSTRING \
we should use consistent name: message-emulator / messaging-emulator

2024-09-18 10:01 UTC, sonwan2020 commented on docs/08_lab_messaging/0801.md
> +          namespace: ${SERVICEBUS_NAMESPACE}
These two variables, SERVICEBUS_NAMESPACE & CLIENT_ID are not set to app?

2024-09-18 10:01 UTC, sonwan2020 commented on docs/08_lab_messaging/0801.md
> +   az role assignment create --assignee $SP_ID --scope $SERVICEBUS_ID --role "Azure Service Bus Data Sender"
for better doc, add links to the page about roles

2024-09-18 10:02 UTC, sonwan2020 commented on docs/08_lab_messaging/0804.md
> +   public class VisitResponse {
@AllArgsConstructor  to simplify code?

2024-09-18 10:02 UTC, sonwan2020 commented on docs/08_lab_messaging/0804.md
> +   public class VisitRequest implements Serializable {
@AllArgsConstructor ?

2024-09-18 10:04 UTC, sonwan2020 commented on docs/08_lab_messaging/0804.md
> +       @JmsListener(destination = "visits-requests")
this destination is hardcoded

2024-09-18 12:34 UTC, vermegi commented on src/pom.xml
> +        <module>spring-petclinic-messaging-emulator</module>
I don't think this should be there from the start. I think the steps in the module let the learner add this as one of the steps/modules.

2024-09-18 12:35 UTC, vermegi commented on src/spring-petclinic-visits-service/pom.xml
> +
Here as well, we should be mindful not to change the base project ... the learner adds these dependencies during the lab steps.

2024-09-18 12:36 UTC, vermegi requested changes

2024-09-18 12:36 UTC, vermegi commented on src/spring-petclinic-visits-service/pom.xml
> +
I guess these are all there for testing the lab steps, but these should NOT be merged into the base src code. 
Either do your tests on a separate branch, but these should be removed from this PR. The PR should only include the 'execution steps' for the learner, we should not merge in the final solution.

2024-09-19 01:51 UTC, haoozhang commented on config/application.yml
> +      pricing-tier: premium
You can see the sample configuration in the above link, just like follows:
```bash
spring:
  jms:
    servicebus:
      connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING}
      pricing-tier: ${PRICING_TIER}
```
https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-jms-support#use-service-bus-connection-string.

Also, if not specify this property, it will fail to create Service Bus Client bean, with following error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceBusJmsProperties' defined in class path resource [com/azure/spring/cloud/autoconfigure/implementation/jms/ServiceBusJmsAutoConfiguration.class]: 'spring.jms.servicebus.pricing-tier' is not valid.
```

2024-09-19 01:55 UTC, haoozhang commented on docs/08_lab_messaging/0801_application.yml
> +  datasource:
Synced with Xiaolu before, the current service connection solution for Service Bus has some bugs. Specifically, it can assign RBAC role for MI to the target resource. However, it injects the wrong configuration in the source service. So, here we explicitly use MI and assign role.

2024-09-19 02:53 UTC, haoozhang commented on docs/08_lab_messaging/0801.md
> +             client-id: ${CLIENT_ID}
updated.

2024-09-19 02:57 UTC, haoozhang commented on docs/08_lab_messaging/0802.md
> +     --env-vars APPLICATIONINSIGHTS_CONNECTION_STRING=$AI_CONNECTIONSTRING APPLICATIONINSIGHTS_CONFIGURATION_CONTENT='{"role": {"name": "api-gateway"}}' InstrumentationKey=$AI_CONNECTIONSTRING \
updated to always use `messaging-emulator`.

2024-09-19 03:00 UTC, haoozhang commented on docs/08_lab_messaging/0801.md
> +          namespace: ${SERVICEBUS_NAMESPACE}
added them when creating container app.

2024-09-19 03:04 UTC, haoozhang commented on docs/08_lab_messaging/0804.md
> +   public class VisitResponse {
updated.

2024-09-19 03:04 UTC, haoozhang commented on docs/08_lab_messaging/0804.md
> +   public class VisitRequest implements Serializable {
updated.

2024-09-19 03:06 UTC, haoozhang commented on docs/08_lab_messaging/0804.md
> +       @JmsListener(destination = "visits-requests")
updated.

2024-09-19 03:06 UTC, haoozhang commented on src/pom.xml
> +        <module>spring-petclinic-messaging-emulator</module>
@sonwan2020 what do you think about it?

2024-09-19 03:07 UTC, haoozhang commented on src/spring-petclinic-visits-service/pom.xml
> +
add @sonwan2020 for this comment

2024-09-19 03:13 UTC, sonwan2020 commented on src/pom.xml
> +        <module>spring-petclinic-messaging-emulator</module>
lets discuss this here https://github.com/Azure-Samples/java-microservices-aca-lab/discussions/40

2024-09-19 03:14 UTC, sonwan2020 commented on src/spring-petclinic-visits-service/pom.xml
> +
please share your ideas here https://github.com/Azure-Samples/java-microservices-aca-lab/discussions/40

2024-09-19 03:24 UTC, sonwan2020 commented on docs/08_lab_messaging/0801_application.yml
> +  datasource:
I mean the database configuration, you don't have to put the url and username here

2024-09-19 05:01 UTC, haoozhang commented on docs/08_lab_messaging/0801_application.yml
> +  datasource:
removed the database configuration due to we have already configured service connection solution for database.

2024-09-19 05:03 UTC, haoozhang commented on docs/08_lab_messaging/0801.md
> +          namespace: ${SERVICEBUS_NAMESPACE}
BTW, these two variables cannot be hardcoded. 
Service bus namespace containers random character.
Client id is a GUID generated by AAD.

2024-09-19 05:09 UTC, haoozhang commented on docs/08_lab_messaging/0801.md
> +   az role assignment create --assignee $SP_ID --scope $SERVICEBUS_ID --role "Azure Service Bus Data Sender"
updated.

2024-09-19 05:24 UTC, sonwan2020 approved these changes

2024-09-19 05:32 UTC, haoozhang commented
Hi @vermegi, for your concern, let's discuss in the #40.
I will merge this PR first, and will update it if necessary if we make a final decision. Thanks!

2024-09-19 05:33 UTC, merged